;Programa que limpia pantalla y escribe una cadena en el renglón12, columna 30.
DATOS SEGMENT PARA 'DATA'
  CADENA  DB      'ESTO ES UNA PRUEBA$'
  REN     DB      12
  COL     DB      30
DATOS ENDS

PILA SEGMENT PARA STACK 'STACK'
  DW      100     DUP(0)
PILA ENDS

CODIGO SEGMENT PARA 'CODE'
  ASSUME  CS:CODIGO, DS:DATOS, SS:PILA, ES:NOTHING

  LIMPIA_PANTALLA PROC NEAR
     MOV AX, 0600H
     MOV BH, 71H
     MOV CX, 0000H
     MOV DX, 184FH
     INT 10H
     RET
  LIMPIA_PANTALLA ENDP

  POSICIONA_CURSOR PROC NEAR
     MOV AH,02
     MOV BH,00
     MOV DH,REN
     MOV DL, COL
     INT 10H
     RET
  POSICIONA_CURSOR ENDP

  LETRERO  PROC NEAR
     MOV AH,09
     LEA DX, CADENA
     INT 21H
     RET
  LETRERO ENDP

  PRINCIPAL PROC FAR
     PUSH DS
     XOR AX, AX
     PUSH AX
     MOV AX, DATOS
     MOV DS, AX
     MOV ES, AX
     CALL LIMPIA_PANTALLA
     CALL POSICIONA_CURSOR
     CALL LETRERO
;     MOV AH,00
;     INT 21H
     RET
  PRINCIPAL ENDP

CODIGO ENDS
  END PRINCIPAL
