; PROGRAMA QUE LEE UNA CADENA HASTA ENCONTRAR UN PUNTO  
DATOS SEGMENT PARA 'DATA'
  REN     DB    10
  COL     DB    5
  CADENA  DB      'PASSWORD: $'
  CAD     DB   10 DUP(0) 
DATOS ENDS

PILA SEGMENT PARA STACK 'STACK'
  DW      100     DUP(0)
PILA ENDS

CODIGO SEGMENT PARA 'CODE'
  ASSUME  CS:CODIGO, DS:DATOS, SS:PILA, ES:NOTHING

  LIMPIA_PANTALLA PROC NEAR
     MOV AX, 0600H
     MOV BH, 71H
     MOV CX, 0000H
     MOV DX, 184FH
     INT 10H
     RET
  LIMPIA_PANTALLA ENDP

  POSICIONA_CURSOR PROC NEAR
     MOV AH,02
     MOV BH,00
     MOV DH,REN
     MOV DL, COL
     INT 10H
     RET
  POSICIONA_CURSOR ENDP



  LETRERO  PROC NEAR
     MOV AH,09
     INT 21H
     RET
  LETRERO ENDP

LEECAR PROC NEAR
     MOV AH,01
     INT 21H
     RET
LEECAR ENDP

LECTURA PROC NEAR
        CALL LEECAR
CICLO1:
        CMP AL, '.'
        JE FIN1
        MOV [SI], AL
        INC SI                               
        CALL LEECAR
        JMP CICLO1     
 FIN1:  RET
LECTURA ENDP


  PRINCIPAL PROC FAR
     PUSH DS
     XOR AX, AX
     PUSH AX
     MOV AX, DATOS
     MOV DS, AX
     MOV ES, AX
     CALL LIMPIA_PANTALLA
     CALL POSICIONA_CURSOR
     LEA DX, CADENA 
     CALL LETRERO
     LEA SI, CAD  
     CALL LECTURA
FIN: RET
  PRINCIPAL ENDP

CODIGO ENDS
  END PRINCIPAL
